---
title: "Compiler Error CS0103 | Microsoft Docs"
ms.custom: ""
ms.date: "11/24/2016"
ms.prod: "visual-studio-dev14"
ms.reviewer: ""
ms.suite: ""
ms.technology: 
  - "devlang-csharp"
ms.tgt_pltfrm: ""
ms.topic: "error-reference"
f1_keywords: 
  - "CS0103"
dev_langs: 
  - "CSharp"
helpviewer_keywords: 
  - "CS0103"
ms.assetid: fd1f2104-a945-4dba-8137-8ef869826062
caps.latest.revision: 13
caps.handback.revision: 13
author: "BillWagner"
ms.author: "wiwagn"
manager: "wpickett"
translationtype: Human Translation
---
# Compiler Error CS0103
[!INCLUDE[vs2017banner](../../../csharp/includes/vs2017banner.md)]

名稱 'identifier' 不存在於目前內容中  
  
 嘗試使用類別、[命名空間](../../../csharp/language-reference/keywords/namespace.md)或範圍中沒有的名稱。  請檢查名稱的拼字，以及您所使用的指示詞和組件參考，來確定您試圖使用的名稱可以使用。  
  
 如果您在迴圈內、 `try`區塊內或 `if` 區塊內宣告一個變數，然後嘗試從封閉程式碼區塊或其他獨立程式碼區塊中存取此變數，如下列範例所示，就會時常發生這種錯誤。  
  
```c#  
using System;  
  
class MyClass1  
{  
    public static void Main()  
    {  
        try  
        {  
            // The following declaration is only available inside the try block.  
            MyClass1 conn = new MyClass1();  
        }  
        catch (Exception e)  
        {  
            // The following expression causes error CS0103, because variable  
            // conn only exists in the try block.  
            if (conn != null)   
                Console.WriteLine("{0}", e);  
        }  
    }  
}  
  
```  
  
 下列範例剖析此錯誤。  
  
```c#  
  
using System;  
  
class MyClass2  
{  
    public static void Main()  
    {  
        // To resolve the error in the example, the first step is to   
        // move the declaration of conn out of the try block. The following  
        // declaration is available throughout the Main method.  
        MyClass2 conn = null;  
        try  
        {  
            // Inside the try block, use the conn variable that you declared  
            // previously.  
            conn = new MyClass2();  
        }  
        catch (Exception e)  
        {  
            // The following expression no longer causes an error, because  
            // the declaration of conn is in scope.  
            if (conn != null)   
                Console.WriteLine("{0}", e);  
        }  
    }  
}  
  
```